### ISSUE TITLE
the docker image seems out of date

### ISSUE THREAD

**Issue by kwjjyn** [vmware/p4c-xdp#104] opened 2019-05-14 13:03 UTC
I use vagrant to download the Ubuntu and run the below command :
```bash
# docker images
```
the output is
```bash
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
u9012063/p4xdp      latest              975d533176d4        2 years ago         2.66GB
```
And then I run the docker image and found there are lots of diffrences between the docker and the git repo.
So for now , I must compile the p4c and extend the compiler using the bash command?  And it seems there are some header including problems when I run the **make** in the ~/p4c/extensions/p4c-xdp/tests

**Comment by williamtu** [comment] 2019-05-16 17:25
yes, let me update the docker image to a more recent version.

**Comment by williamtu** [comment] 2019-05-16 18:08
I've created a latest docker image, please do:
```bash
p4c-xdp# docker pull u9012063/p4cxdp:p4c-xdp-2019
p4c-xdp# docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
u9012063/p4cxdp     p4c-xdp-2019        2fc1869a722d        24 minutes ago      1.54GB
```

**Comment by kwjjyn** [comment] 2019-05-17 03:34
Great, thanks！
While I pull the new docker image and run the below command in the p4c/extensions/p4c-xdp/tests,
```bash
# make
```
some errors occurred in xdp7.c , and the output is :
```bash
[...]
p4c-xdp --Werror -I ../p4include -I../../../backends/ebpf/runtime/ --target xdp -o xdp7.c xdp7.p4;
clang -I ../p4include -I../../../backends/ebpf/runtime/\
        -D__KERNEL__ -D__ASM_SYSREG_H -Wno-unused-value -Wno-pointer-sign \
        -Wno-compare-distinct-pointer-types \
        -Wno-gnu-variable-sized-type-not-at-end \
        -Wno-tautological-compare \
        -O2 -emit-llvm -g -c xdp7.c -o -| llc -march=bpf -filetype=obj -o xdp7.o
error: xdp7.c:191:34: in function ebpf_filter i32 (%struct.xdp_md*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.

error: xdp7.c:102:20: in function ebpf_filter i32 (%struct.xdp_md*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.

error: xdp7.c:258:47: in function ebpf_filter i32 (%struct.xdp_md*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
[...]
```
do you know why this happened?

**Comment by kwjjyn** [comment] 2019-05-17 06:35
Besides, when I run the below command to load the .o file into the kernel :
```bash
# ip link set dev lo xdp obj xdp4.o verb 
```
there're some errors occurred :
```bash
Note: 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
Map specification differs from pinned file!
 - Size key:     16 (obj) != 8 (pin)

Map 'Ingress_dstmactable' self-check failed!
Error loading maps into kernel!
Error fetching ELF ancillary data!
```
and the xdp programs after xdp4 have the same probelm.

**Comment by mbudiu-vmw** [comment] 2019-05-20 18:04
You should open different issues.
The stack size is a problem with the way bcc/llvm generate code; we discussed this in #43.
This other error I have never seen.
@williamtu : can you reproduce this error?

**Comment by williamtu** [comment] 2019-05-20 18:11
As for the issue about "Note: 8 bytes struct bpf_elf_map fixup performed due to size mismatch!"
It's due to previous map not being cleaned up.
So probably your previous xdp program uses key=16 byte, and now 
```
ip link set dev lo xdp obj xdp4.o verb
```
loads a map with key=8 byte.

Can you run commands like:
```
ip link set dev lo xdp off
```
and try again?

**Comment by williamtu** [comment] 2019-05-28 21:05
Does it work for you?

**Comment by kwjjyn** [comment] 2019-05-29 02:33
I try to shutdown the xdp program using the command . But it doesn't work for me. 
Actually, I didn't use the docker image later. I use the command to extend the p4c compiler. And run these programs on my 4.18 kernel , it works.

**Comment by kwjjyn** [comment] 2019-05-29 07:11
Hi, in fact , when I  attach the  xdp3.o  after attach the xdp2.o and deattach the xdp2.o by xdp off command,   there's still the same error :
```
8 bytes struct bpf_elf_map fixup performed due to size mismatch!
```
and this time , I found that the maps stored in the /sys/fs/bpf/xdp/globals/ still exist . These old maps created by the xdp2.o didn't be deleted by the 
```
ip link set dev ens3 xdp off
```
After I delete all these old maps,  the xdp3.o program can be loaded without any errors.

**Comment by mbudiu-vmw** [comment] 2019-05-30 23:59
I assume that we can close this issue.

**Closed by mbudiu-vmw** 2019-05-30 23:59 UTC
